name: OSTORLAB

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]  

permissions:
  contents: read

jobs:
  build:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Launch Ostorlab scan
      id: start_scan
      uses: Ostorlab/ostorlab_actions@de9e694274bcecdaea6c7169e24fe74bc1b483c6
      with:
        scan_profile: fast_scan 
        asset_type: android-apk 
        target: app/build/outputs/apk/debug/app-debug.apk
        scan_title: title_scan_ci
        ostorlab_api_key: ${{ secrets.ostorlab_api_key }} # your secret api key.
        break_on_risk_rating: HIGH 
        max_wait_minutes: 20 
